### ISSUE TITLE
Update to support vSphere 7.0 U2

### ISSUE THREAD

**Issue by Coder84619** [rutgerblom/vsphere-nsxt-lab-deploy#151]
Any plans to update the config files and test vSphere 7.0 U2?

**Comment by rutgerblom** [comment]
We are in the process of adding support for 7.0 U2. Currently we are working with the code in the dev-v3 branch and hopefully we can add 7.0 U2 support there soon.

**Comment by luischanu** [comment]
@Coder84619, the issues with vSphere 7.0 Update 2 have been addressed in the current "dev-v3" branch, and it now deploys successfully.
