### ISSUE TITLE
Cannot fetch ISO from Directory Structure

### ISSUE THREAD

**Issue by Mybarry** [rutgerblom/vsphere-nsxt-lab-deploy#182]
Im trying to install my first pod, but the Playbook is complaining it cannot find the iso images. This is the error Im getting:
=================================== Configuration Issue Found ===================================

              Issue: vCenter Server installer file could not be found at specified path

  Full Path To File: /Software/VMware/vCenter/v7.0.0U2A/VMware-VCSA-all-7.0.2-17920168.iso
===============================================================
But the iso's are  populated:
root@ansible-controller:/Software/VMware/vCenter/v7.0.0U2A# pwd
/Software/VMware/vCenter/v7.0.0U2A
root@ansible-controller:/Software/VMware/vCenter/v7.0.0U2A# ls -l
total 7808912
-rw-rw-r-- 1 root root 7996319744 Jun 16 17:31 VMware-VCSA-all-7.0.2-17958471.iso

What am I doing wrong?  Any help appreciated

**Comment by rutgerblom** [comment]
Hi,

VMware-VCSA-all-7.0.2-17920168.iso is vCenter **7.0 U2A**
VMware-VCSA-all-7.0.2-17958471.iso is vCenter **7.0 U2B**

It seems like you have the vCenter **7.0 U2B** ISO in your  /Software/VMware/vCenter/**v7.0.0U2A** directory. 

If you place the VMware-VCSA-all-7.0.2-17920168.iso (7.0 U2A) in that directory it will work.

Kind regards,
Rutger

**Comment by Mybarry** [comment]
Rutger,
You are correct.  Sorry for being so sloppy. Let me validate my iso's agains the directory structure. Thanks for your prompt reply!
