### ISSUE TITLE
Deployment of DNS Server fails

### ISSUE THREAD

**Issue by vBrit** [rutgerblom/vsphere-nsxt-lab-deploy#273]
This worked in the past fine, but using dev-v5 (Didn't create since v2) I am seeing an error on the Console of the DNS server.
![sddc-dns-error](https://user-images.githubusercontent.com/81189935/178081119-3186e388-ef2d-424f-ab1b-04e518cc1611.jpg)

[1657321722.757726669.install_fail.crash.txt](https://github.com/rutgerblom/SDDC.Lab/files/9075460/1657321722.757726669.install_fail.crash.txt)

Attached is the crash file

**Comment by rutgerblom** [comment]
Hi,

It seems that the "install dns-server^" command returned an error here. I tried to reproduce this on a new Ubuntu Server but there the command works fine.

Could there have been a temporary problem with Internet connectivity or the Ubuntu repository? Have you tried it more than once?

Kind regards,
Rutger

**Comment by vBrit** [comment]
I didn't see any errors to indicate Internet/repo errors. I did at the time try and deploy it multiple times. 

I can see about redeploying it sometime this week. Thanks

**Comment by rutgerblom** [comment]
We believe we have identified the issue and implemented a workaround in the latest dev-v5 PR. Could you pull the latest dev-v5 code and give it another try at your earliest convenience?

Thank you.
