### ISSUE TITLE
TASK [Create a Management Distributed Port-Group in vCenter] fails

### ISSUE THREAD

**Issue by ghost** [rutgerblom/vsphere-nsxt-lab-deploy#314]
ii'm trying to deploy new pod with new v5 but it fails with error:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "lab-m01-vcsa01.sworks.lab",
            "in_traffic_shaping": null,
            "mac_learning": null,
            "net_flow": null,
            "network_policy": {
                "forged_transmits": true,
                "inherited": null,
                "mac_changes": false,
                "promiscuous": true
            },
            "num_ports": null,
            "out_traffic_shaping": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "port_allocation": null,
            "port_binding": "static",
            "port_policy": {
                "block_override": true,
                "ipfix_override": false,
                "live_port_move": false,
                "network_rp_override": false,
                "port_config_reset_at_disconnect": true,
                "security_override": false,
                "shaping_override": false,
                "traffic_filter_override": false,
                "uplink_teaming_override": false,
                "vendor_config_override": false,
                "vlan_override": false
            },
            "portgroup_name": "Pod-240-Mgmt",
            "proxy_host": null,
            "proxy_port": null,
            "state": "present",
            "switch_name": "sddc-lab-vds01",
            "teaming_policy": {
                "active_uplinks": null,
                "inbound_policy": null,
                "load_balance_policy": "loadbalance_srcid",
                "notify_switches": true,
                "rolling_order": false,
                "standby_uplinks": null
            },
            "username": "administrator@vsphere.local",
            "validate_certs": false,
            "vlan_id": "240",
            "vlan_private": false,
            "vlan_trunk": false
        }
    },
    "msg": "missing required arguments: inherited found in network_policy"
}

Also tried to create two "fresh" ubuntu (22.04 and 20.04) VMs but the result is always the same.

Thanks!

**Comment by luischanu** [comment]
Hello @na2626,
I am guessing that you are using outdated VMware vSphere Ansible module versions.   When we upgraded to newer modules, I recall that an argument was no longer needed, so it was removed.   This should be documented in the CHANGELOG.md file regarding that change.   Regardless, I believe if you upgrade you're modules, the issue should resolve.  See the README for steps on upgrading all of your modules to the current versions.

**Comment by ghost** [comment]
Hello Luis,

Thanks for your reply. I updated modules

* Install the required software on your Ansible controller:
  * ```sudo apt update```
  * ```sudo apt install python3 python3-pip python-is-python3 xorriso git```
  * ```git clone https://github.com/rutgerblom/SDDC.Lab.git ~/git/SDDC.Lab```
  * ```pip3 install --upgrade -r ~/git/SDDC.Lab/pip3_requirements.txt```

* Update your PATH environment variable by doing the following:
  * Logout of your Ansible controller
  * Login to your Ansible controller

* Install Ansible collections on your Ansible controller:
  * ```ansible-galaxy collection install --upgrade -r ~/git/SDDC.Lab/requirements.yml```




On both my ubuntu VM but the result is the same.

Thanks for your help

**Comment by rutgerblom** [comment]
Hello @na2626,

Could you share the output of the following commands:

`pip3 list | grep vSphere-Automation-SDK`

`ansible --version`

`ansible-galaxy collection list community.vmware`

Thanks.

**Comment by ghost** [comment]
Hello Rutger,

Here’s the output:

 ➜  ~ pip3 list | grep vSphere-Automation-SDK
vSphere-Automation-SDK             1.79.0

 ➜  ~ ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/home/labadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/labadmin/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/labadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/labadmin/.local/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True

 ➜  ~ ansible-galaxy collection list community.vmware



# /home/labadmin/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.vmware 3.0.0

# /home/labadmin/.local/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.vmware 2.10.0


Thanks

**Comment by luischanu** [comment]
@na2626 ,
Not related to your issue, but you might want to upgrade your Jinja, as I noticed some slight speed increases with the newer version.  Just thought I'd mention that as a FYI.

**Comment by ghost** [comment]
Thanks Luis, latest jinja2 3.1.2 will be ok?

**Comment by luischanu** [comment]
Yes...that's the version of Jinja that I am running.

**Comment by luischanu** [comment]
@na2626 , when you stated "**_Also tried to create two "fresh" ubuntu (22.04 and 20.04) VMs but the result is always the same._**", I'm assuming that you the two newly built Ubuntu boxes you're referencing are for your Ansible controller, and not Ubuntu workloads (i.e. DNS server) that you're trying to deploy via SDDC.Lab.  Can you confirm that is what you mean?

FYI, about a month ago I built a new Ansible controller (v22.04) to test out the installation instructions in the README file, and I didn't have any issues.   Everything worked as expected, and I was able to deploy a Pod.  I already had my SDDC.Lab DNS server in place and working, and all I provisioned was the Ansible controller.

**Comment by ghost** [comment]
Yes, I’m referencing ansible controller. Also I also have dns server in place from previous deploy Inviato da iPhoneIl giorno 18 ott 2022, alle ore 03:49, Luis Chanu ***@***.***> ha scritto:﻿
@na2626 , when you stated "Also tried to create two "fresh" ubuntu (22.04 and 20.04) VMs but the result is always the same.", I'm assuming that you the two newly built Ubuntu boxes you're referencing are for your Ansible controller, and not Ubuntu workloads (i.e. DNS server) that you're trying to deploy via SDDC.Lab.  Can you confirm that is what you mean?
FYI, about a month ago I built a new Ansible controller (v22.04) to test out the installation instructions in the README file, and I didn't have any issues.   Everything worked as expected, and I was able to deploy a Pod.  I already had my SDDC.Lab DNS server in place and working, and all I provisioned was the Ansible controller.

**Comment by rutgerblom** [comment]
Thanks @na2626 for providing the output. There seems to be some kind of issue or change with the latest community.vmware collection (version 3.0.0). 

While we investigate how to solve this you can implement a workaround by downgrading the community.vmware collection to version 2.9.1 which we know is working:

`ansible-galaxy collection install community.vmware:==2.9.1`

Let us know if this solves the problem for you.

**Comment by ghost** [comment]
Thanks Rutger! This seems to solve the issue but now I see that the vyos config isn’t copied and the subsequent phases fail. On vyos only the eth0 (uplink) ip is configured.

**Comment by luischanu** [comment]
@na2626, did you read through the "Upgrade Considerations" section in the README file for "v4 to v5", and follow the VyOS instructions listed there?

I just tested the LATEST build of VyOS, and it worked just fine.   Please see the "Upgrade Considerations" section mentioned above.

If you have, and are still having issues, please open a new Issue for the VyOS issue.  Thanks!

**Comment by luischanu** [comment]
@na2626, there appears to be something up with the router configuration.  When I manually tested it last night, it worked, but in a recent deployment, the configuration doesn't apply.  I just wanted to let you know.  I'm looking into it.  As this thread open issue is about the vDS Port-Group, I will not be responding any more on this here.  Keep an eye out in the CHANGELOG, or, open another issue for the VyOS Pod-Router not getting configured, and we can continue the discussion there.  Thank you!

**Comment by luischanu** [comment]
@na2626, found issue with latest VyOS module (v4.0.0) released 5 days ago.  Revert back to v3.0.1, and problem is solved.  See CHANGELOG.md in 'dev-v6' branch for details.  Considering this issue resolved.

**Comment by ghost** [comment]
Thank you very much Rutger & Luis, you're doing a really good job with this project!
