### ISSUE TITLE
deploy additional hosts

### ISSUE THREAD

**Issue by ghost** [rutgerblom/vsphere-nsxt-lab-deploy#337]
Hello, would it be possible to deploy additional hosts to existing deployment ? For example is I do not deploy Compute B initially or if I need more hosts in a specific cluster?
Thanks!

**Comment by rutgerblom** [comment]
Hello @na2626, currently it's not possible to do this but we are looking into ways to add a feature  like that to the project in a future release. 

Best regards 
Rutger

**Comment by ghost** [comment]
Hello Rutger,Thanks for replying. It would be a useful feature and a great ‘add-on’ to an excellent project like this! Kind regards Nicola Il giorno 3 nov 2022, alle ore 20:33, Rutger Blom ***@***.***> ha scritto:﻿
Hello @na2626, currently it's not possible to do this but we are looking into ways to add a feature  like that to the project in a future release.
Best regards
Rutger
