### ISSUE TITLE
Only version of NSX 4 on VMUG isn't listed in software.yml for dev-v6

### ISSUE THREAD

**Issue by travellingtechie** [rutgerblom/vsphere-nsxt-lab-deploy#377]
Currently the only version of NSX 4 I can download from VMUG advantage is nsx-unified-appliance-4.1.0.0.0.21333676-le.ova which isn't listed in the software.yml file.

I added it as
```
        "4.1.0.0":
          Name: NSX Transformers v4.1.0.0
          File: nsx-unified-appliance-4.1.0.0.0.21333676-le.ova
          Location:
            Local: "{{ RootDirectory }}/VMware/NSX-T/v4.1.0.0"
            URL:
          Version: "4.0"
          FileExt: ova
```
Hopefully that is correct

**Comment by luischanu** [comment]
Other than also adding your license key in the licenses.yml file, creating the NSX entry in the software.yml file as you indicated should be all that is needed.

FYI, I don’t think we have tested any LE versions, so please let us know how it goes.

Good luck, and great to see another SDDC.Lab user.

—Luis Chanu

**Comment by travellingtechie** [comment]
what exactly does LE mean?  I'll let you know how it goes, but it'll be a bit, as I'm running on AMD processors I also have to figure out how to inject the AMD Ryzen fix in to the ansible code.

**Comment by luischanu** [comment]
It stands for “Limited Export”.

**Comment by travellingtechie** [comment]
Well the LE testing didn't last very long.  I deployed it manually in to my lab and tried to create a VPN, and it wouldn't let me.  I was able to download the full version from the VATC page (I'm a VCI), so I'm starting over.   I think we can close this and I'll post another one with the code for AMD processors once I get that worked out.
