### ISSUE TITLE
ALB will not successfully deploy without content library

### ISSUE THREAD

**Issue by rexit1982** [rutgerblom/vsphere-nsxt-lab-deploy#409]
In my setup I am not deploying a content library.  The ALB automation appears to assume there is one and is not doing any checks around that.  This causes the vcenter cloud to be in an error state and some later api calls yeild empty info resulting in {{ vsphere_cluster_url }} being empty and the default group SEG settings task to fail ending the deployment.

I see 3 remediation optionsbut rher could be more. 
1) Put a Check at the beginning of the alb deployment process to see if the expected content library is there.  If not display an error/pause and allow the rest of the deployment to continue.
2) Don't use content library
3) Adapt to use content library if provisioned and do not use it if CL deploy is not true.

Thoughts?

**Comment by rutgerblom** [comment]
Thanks for pointing this out. For now I've added checks to `playbooks/ValidateConfiguration.yml` so that this missing dependency is detected before starting a pod deployment.

**Comment by rutgerblom** [comment]
Updated `playbooks/ValidateConfiguration.yml` to detect and give user a chance to handle this missing dependency before pod deployment is started.

**Comment by rexit1982** [comment]
I would have fixed it!  Just wanted to know long term preference.  If you have thoughts I can do a more advanced improvement.

**Comment by rutgerblom** [comment]
Right now we would like to use the content library so that SEs are deployed automatically. As you know, without content library the user would have to deploy the SEs manually which works fine too of course but in this project we focus a lot on automating things. Thoughts?

**Comment by luischanu** [comment]
@rutgerblom, I agree with your comment above.  We want to focus on automating things, and ensure the SEs are deployed automatically.

**Comment by rexit1982** [comment]
Should it be caught during config generation or early at runtime? It's a
bummer to run for over an hour and hit an error.

Could also create a CL just for alb automatically when it is true to fit
that need so alb deployment is atomic.

**Comment by rutgerblom** [comment]
Yes it's been added to` playbooks/ValidateConfiguration.yml` so we catch this before pod gets deployed.
