### ISSUE TITLE
Playbook Util_CreateSoftwareDir.yml failing.

### ISSUE THREAD

**Issue by vBrit** [rutgerblom/vsphere-nsxt-lab-deploy#426]
Created a new Ansible controller with ubuntu desktop 22.0.4 to run v6 SDDC, I keep getting an error message when I try to create the folder structure. I reach out to Luis and said maybe something to do with the vyos lookup. I commented out the vyos in the software.yml, after which I was able to create the folder structure except vyos.

Error as following, 
Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://api.github.com/repos/vyos/vyos-rolling-nightly-builds/releases/latest : HTTP Error 403: rate limit exceeded. Received HTTP error for https://api.github.com/repos/vyos/vyos-rolling-nightly-builds/releases/latest : HTTP Error 403: rate limit exceeded\n\nThe error appears to be in '/home/kn-ansiblectrl/git/SDDC.Lab/utils/Util_CreateSoftwareDir.yml': line 38, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n##\n    - name: Create VMware vCenter directories\n      ^ here\n"}

I ran the following **ansible-playbook --ask-become-pass ~/git/SDDC.Lab/utils/Util_CreateSoftwareDir.yml**

**Comment by rutgerblom** [comment]
Hi vBrit, I'm seeing the same issue on my side. I will start investigating this.

**Comment by rutgerblom** [comment]
Updated the script after investigating. It's working again.
