### ISSUE TITLE
DNS Failing

### ISSUE THREAD

**Issue by vBrit** [rutgerblom/vsphere-nsxt-lab-deploy#427]
I am trying to spin up a new Pod-010 using v6. It fails at the same place, when it's trying to create vSAN reverse lookup I think. At first, I thought maybe it was because I didn't deploy a new DNS Server. I created a new DNS Server, and I got the same results. 

I turned on display variables in the playbook to help troubleshoot.

I turned on logging and this is the file.
[SDDCLab_playbook.log](https://github.com/rutgerblom/SDDC.Lab/files/14540838/SDDCLab_playbook.log)
this file is with vvv
[SDDCLab_playbook_vvv.log](https://github.com/rutgerblom/SDDC.Lab/files/14541004/SDDCLab_playbook_vvv.log)

Thanks

**Comment by rutgerblom** [comment]
Hi vBrit, I'm unable to reproduce this one. 
Could you post the output of `ansible-galaxy collection list` and `ansible --version` on your Ansible controller?

Thanks

**Comment by vBrit** [comment]
Hi @rutgerblom 
[ansible_version.txt](https://github.com/rutgerblom/SDDC.Lab/files/14547861/ansible_version.txt)
[ansible-galaxy_collection.txt](https://github.com/rutgerblom/SDDC.Lab/files/14547862/ansible-galaxy_collection.txt)

See attached, need anything else let me know :)

Thanks

**Comment by rutgerblom** [comment]
Some typos in one of the j2 templates caused this issue. DNS server deployment is working again.
