### ISSUE TITLE
NSX 4.2.1.0.0.24304122 fails to start Group Type: MONITORING cluster role when deployed with small form factor

### ISSUE THREAD

**Issue by rvanderwouw** [rutgerblom/vsphere-nsxt-lab-deploy#467]
When using the newest NSX version 4.2.1.0.0.24304122 combined with a small form factor, a POD-Deployment fails because for an unknown reason (I was unable to determine the cause of the problem) the clustering role "MONITORING" was unable to start successfully. This causes the deployment to fail because the NSX cluster never reaches the stable state.
I was able to remediate the problem by switching to a "medium"-form factor, which went completely fine. 
I verified that this is actually not a SDDC.Lab problem but a NSX problem by deploying the NSX OVA manually with the same settings. 
I do not think there is a fix to be made in this project, but it might be added to the list of known issues unless Broadcom fixes the small form factor deployment. All previous deployments in our lab with earlier version went fine with the small form factor.

**Comment by rutgerblom** [comment]
Hey Rob, Thanks for reporting this. You are correct and in the next release (v8) we actually increased the Edge node size to medium by default. Feel free to give [dev-v8](https://github.com/rutgerblom/SDDC.Lab/tree/dev-v8) a spin if you want.
